sudo: false

addons:
  apt:
    packages:
      - git
      - curl
      - make
      - build-essential
      - autoconf
      - autotools-dev
      - libconfuse-dev
      - swig
      - python-dev
      - python3-pip
      - python3-pytest
      - mtools

install: "pip3 install --user -r utils/requirements.txt"

before_script: curl https://sh.rustup.rs -sSf | sh -s -- -y && "$HOME/.cargo/bin/cargo" install subcomponent

script: env PATH="$HOME/.cargo/bin:$PATH" python3 -m pytest -vs --maxfail=1
