sudo: false

language: python
python:
  - "3.5"

addons:
  apt:
    packages:
      - git
      - curl
      - make
      - build-essential
      - autoconf

install: "pip install jinja2 pyyaml jsonschema"

script: env PATH="$HOME/.cargo/bin:$PATH" pytest
