sudo: false

language: python
python:
  - "3.5"

addons:
  apt:
    packages:
      - git
      - curl
      - make
      - build-essential
      - autoconf
      - autotools-dev
      - libconfuse-dev

install: "pip install jinja2 pyyaml"

before_script: curl https://sh.rustup.rs -sSf | sh -s -- -y && "$HOME/.cargo/bin/cargo" install subcomponent

script: env PATH="$HOME/.cargo/bin:$PATH" pytest -vs
