# Copyright (c) 2016, Jean Guyomarc'h <jean.guyomarch@gmail.com>
#
# This file is part of SBXG
#
# SBXG is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# SBXG is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with SBXG.  If not, see <http://www.gnu.org/licenses/>.

sudo: true

branches:
   only:
      - master
      - /^testing\/.*$/

addons:
   apt:
      sources:
         - r-packages-trusty
      packages:
         - realpath
         - git
         - parted
         - apt-utils
         - gcc-arm-linux-gnueabihf
         - autoconf
         - build-essential
         - make
         - automake
         - debootstrap
         - qemu-user-static
         - qemu
         - binfmt-support
         - kernel-package
         - u-boot-tools
         - sudo
         - kpartx
         - libncurses5-dev
         - curl

before_script:
   - sudo apt-get install kpartx kernel-package parted
   - mkdir -p "$HOME/bin"
   - curl https://storage.googleapis.com/git-repo-downloads/repo > "$HOME/bin/repo"
   - chmod a+x "$HOME/bin/repo"
   - export PATH="$HOME/bin:$PATH"
   - git config --global user.name "travis"
   - git config --global user.email "$(whoami)@$(hostname).ci"
   - git config --global color.ui "false"

script: travis_wait 30 ./tests/run --no-cleanup --branch "$TRAVIS_BRANCH"
