#! /usr/bin/env sh
#
# Copyright (c) 2016, Jean Guyomarc'h <jean.guyomarch@gmail.com>
#
# This file is part of SBXG
#
# SBXG is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# SBXG is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with SBXG.  If not, see <http://www.gnu.org/licenses/>.


set -x

# Try to determine the distribution
. /etc/os-release
if [ $? -ne 0 ]; then
   echo "*** Cannot determine the Linux distribution"
   # This is not a failure!
fi
if [ "x$NAME" = "xDebian" ]; then
   IS_DEBIAN=1
else
   IS_DEBIAN=0
fi

# Enable script errors only from here
set -e
set -u

TOP_SRC_DIR="$(realpath "$(dirname "$0")/../")"
SBXG_URL="https://github.com/sbxg/sbxg.git"
CONFIG="$TOP_SRC_DIR/tests/config.travis"


err() {
   echo "*** $@" 1>&2
}

#==============================================================================#
#                                    Getopt                                    #
#==============================================================================#

usage() {
   echo "Usage: $0 [OPTIONS]"
   echo "  -c=,--config=  specify the configuration os SBXG"
   echo "  -l,--local     run tests locally"
   echo "  -h,--help      show this message"
   exit "$1"
}

test_arg() {
   if [ $# -le 1 ]; then
      err "Missing argument to \"$1\""
      usage 1
   fi
}

while [ $# -gt 0 ]; do
   case "$1" in
      (-h|--help)
         usage 0
         ;;
      (-l|--local)
         SBXG_URL="file://$TOP_SRC_DIR"
         ;;
      (-c|--config)
         test_arg $*
         shift
         CONFIG="$(realpath "$1")"
         ;;
      (*)
         err "Invalid arguments"
         usage 1 1>&2
         ;;
   esac
   shift
done


#==============================================================================#
#                      Run Tests in a Temporary Directory                      #
#==============================================================================#

export MANIFESTS_URL="$SBXG_URL"
export MANIFESTS_REVISION="$TRAVIS_BRANCH"

cd "$TOP_SRC_DIR"

cp "$CONFIG" .config
cp tests/makefile.vars makefile.vars.override

make init sync
make all

if [ "$IS_DEBIAN" -eq 1 ]; then
   make debian
fi

make mrproper
