#! /usr/bin/env sh
#
# Copyright (c) 2015-2016, Jean Guyomarc'h <jean@guyomarch.bzh>
#
# This file is part of SBXG
#
# SBXG is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# SBXG is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with SBXG.  If not, see <http://www.gnu.org/licenses/>.


if [ $# -lt 1 ]; then
   echo "*** Usage: $0 <commands>" 1>&2
   exit 1
fi

CWD="$(realpath "$(dirname "$0")")"
TOP_DIR="$(realpath "$CWD/../")"


set -x
docker run --rm --privileged -t -i -v "$TOP_DIR":/opt/sbxg "sbxg" /bin/bash -c "$(echo "$@")"
